
float64 dt                      #time between control inputs
float64[] roll                  # degrees
float64[] pitch                 # degrees
float64[] yaw                   # degrees
float64[] roll_rate             # degrees / second
float64[] pitch_rate            # degrees / second
float64[] yaw_rate              # degrees / second
float64[] thrust                # 0-1 normalized
float64[] vx                    #meters/second
float64[] vy                    #meters/second
float64[] vz                    #meters/second
float64[] x                     #meters
float64[] y                     #meters
float64[] z                     #meters
int8 idx                        #idx of control input
